---
title: "Correlation Analysis"
output:
  html_notebook:
    code_folding: show
    fig_caption: yes
    theme: united
    toc: yes
---

## Motor Trend Car Road Tests

```{r}
head(mtcars)
```

```{r}
cor(mtcars)
```

```{r}
library(corrplot)
corrplot(cor(mtcars), method="color")
```

```{r}
library(corrplot)
corrplot(cor(mtcars), method="number")
```

```{r}
library(corrplot)
corrplot(cor(mtcars), method="pie")
```

```{r}
library(corrplot)
corrplot(cor(mtcars), method="circle")
```

```{r}
corrplot.mixed(cor(mtcars))
```

```{r}
corrplot(cor(mtcars), order="hclust")
```


```{r}
mtcarsCorMtest <- cor.mtest(mtcars, conf.level = .95)
mtcarsCorMtest
```


```{r}
corrplot(
  cor(mtcars),
  p.mat = mtcarsCorMtest$p, 
  sig.level = .05,
  order = "hclust", 
  addrect = 3
)
```

## Pearson's product-moment correlation

```{r}
cor.test(
  mtcars$mpg, 
  mtcars$wt,
  alternative = "two.sided",
  method = "pearson",
  conf.level = 0.95
)
```

## Kendall's rank correlation

```{r}
cor.test(
  mtcars$mpg, 
  mtcars$wt,
  alternative = "greater",
  method = "kendall",
  conf.level = 0.9,
  exact = FALSE
)
```

## Spearman's rank correlation

```{r}
cor.test(
  mtcars$mpg, 
  mtcars$wt,
  alternative = "less",
  method = "spearman",
  conf.level = 0.8,
  exact = FALSE
)
```